### ISSUE TITLE
3.0.0更新建议收集

### ISSUE THREAD

**Issue by handy-git** [handy-git/PlayerTitleVersions#1]
初步计划：
1. 全gui自定义功能
每个gui的按钮都能自定义，排版什么的都能，并且可有返回按钮，方便返回上一层菜单
2. 添加初始化.yml
可以在yml中配置好称号直接一键自动初始化出来
3. 在聊天框中点击编辑称号各种信息-类似cmi的 全息图那样编辑
4. 优化自定义称号功能
5. 命令简化

**Comment by modcrafts** [comment]
**开源**
