### ISSUE TITLE
提供玩家已拥有的所有称号的查询API

### ISSUE THREAD

**Issue by xiaoyv404** [handy-git/PlayerTitleVersions#2]
输入玩家名称
返回玩家所拥有的所有称号的List，返回值可以是List<ID>

**Comment by handy-git** [comment]
> 输入玩家名称 返回玩家所拥有的所有称号的List，返回值可以是List

称号的什么信息? ID还是名称,还是全部

**Comment by xiaoyv404** [comment]
> 称号的什么信息? ID还是名称,还是全部

对于我来说的话ID就足够了

**Comment by handy-git** [comment]
> > 称号的什么信息? ID还是名称,还是全部
> 
> 对于我来说的话ID就足够了

好的,我会添加,在3.4.1版本,你可以提前加Q私聊我获取测试版本
