### ISSUE TITLE
3.5.3——3.5.4版本都没有打包好的jar文件

### ISSUE THREAD

**Issue by xiaoniangaoh** [handy-git/PlayerTitleVersions#3]
请问可以打包一下不？

**Comment by handy-git** [comment]
你可以在以下渠道进行下载
https://www.spigotmc.org/resources/playertitle-free-version.78048/
https://www.mcbbs.net/thread-1004671-1-1.html
https://afdian.net/item/8aacfbc8589a11eca01952540025c377
