### ISSUE TITLE
建议增加变量，获取称号原始文本

### ISSUE THREAD

**Issue by SeemWind** [handy-git/PlayerTitleVersions#4]
以便配合其他插件使用minimessage等格式

**Comment by handy-git** [comment]
你是不是需要这些变量？

https://ricedoc.handyplus.cn/wiki/PlayerTitle/papi/

<img width="810" alt="image" src="https://github.com/handy-git/PlayerTitleVersions/assets/32837980/5093f220-6765-426c-a8a9-71e8c5278acf">

**Comment by SeemWind** [comment]
不。这是%luckperms_prefix%返回的内容
![image](https://github.com/handy-git/PlayerTitleVersions/assets/50366675/ce4c5533-6641-4c48-9a4c-7d843a0949c6)
这是%playerTitle_use%返回的内容
![image](https://github.com/handy-git/PlayerTitleVersions/assets/50366675/07f5f8b8-cf6c-4f90-9b51-b36a8762c176)
我希望有一个变量直接返回原始字符串。或者plt可以支持minimessage和minedown，在配置文件中切换使用的格式？

**Comment by handy-git** [comment]
> minimessage和minedown

minimessage和minedown是什么？有wiki吗，我看看

**Comment by handy-git** [comment]
4.0.8 会更新，目前搞完了，但是没人测试，有需要可以qq联系我

**Comment by SeemWind** [comment]
> 4.0.8 会更新，目前搞完了，但是没人测试，有需要可以qq联系我

哪里可以联系到你的qq

**Comment by handy-git** [comment]
4.0.8 已发布
